# Generated by Django 3.2.3 on 2021-06-01 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210601_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likedUsers',
            field=models.ManyToManyField(blank=True, related_name='likedposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
