# Generated by Django 3.2.3 on 2021-06-01 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210601_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_network_customuser_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
